import { z } from "zod";
import { publicProcedure } from "../../../create-context";

export const getGenresProcedure = publicProcedure
  .input(
    z.object({
      approved_only: z.boolean().optional().default(true),
      parent_id: z.string().optional(),
      search: z.string().optional(),
      limit: z.number().optional().default(100),
      offset: z.number().optional().default(0),
    })
  )
  .query(async ({ input, ctx }) => {
    console.log("[genres.getGenres] Fetching genres", input);

    const genres = [
      {
        id: "1",
        name: "Pop",
        slug: "pop",
        description: "The most popular and mainstream music genre featuring catchy melodies, memorable hooks, and wide appeal.",
        color: "#FF0080",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 1000,
        artist_count: 150,
        subgenres: ["Dance Pop", "Electropop", "Indie Pop", "K-Pop", "Teen Pop", "Synth Pop"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "2",
        name: "Rock",
        slug: "rock",
        description: "Powerful guitar-driven music with strong rhythms and rebellious spirit.",
        color: "#8B5CF6",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 850,
        artist_count: 120,
        subgenres: ["Classic Rock", "Alternative Rock", "Indie Rock", "Hard Rock", "Punk Rock", "Progressive Rock"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "3",
        name: "Hip-Hop",
        slug: "hip-hop",
        description: "Urban music featuring rap vocals, beats, and rhythmic poetry.",
        color: "#3B82F6",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 920,
        artist_count: 180,
        subgenres: ["Trap", "Conscious Hip-Hop", "Gangsta Rap", "Alternative Hip-Hop", "Mumble Rap", "Old School"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "4",
        name: "Electronic",
        slug: "electronic",
        description: "Music produced using electronic instruments and digital technology.",
        color: "#10B981",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 780,
        artist_count: 95,
        subgenres: ["House", "Techno", "Dubstep", "Trance", "EDM", "Drum & Bass"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "5",
        name: "Jazz",
        slug: "jazz",
        description: "Sophisticated music characterized by improvisation, swing rhythms, and complex harmonies.",
        color: "#F59E0B",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 650,
        artist_count: 85,
        subgenres: ["Bebop", "Smooth Jazz", "Fusion", "Cool Jazz", "Free Jazz", "Latin Jazz"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "6",
        name: "R&B",
        slug: "r-and-b",
        description: "Rhythm and Blues featuring soulful vocals, smooth melodies, and groovy rhythms.",
        color: "#EC4899",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 720,
        artist_count: 110,
        subgenres: ["Contemporary R&B", "Neo-Soul", "Alternative R&B", "Funk", "Soul"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "7",
        name: "Country",
        slug: "country",
        description: "American roots music featuring storytelling, acoustic instruments, and heartfelt lyrics.",
        color: "#6366F1",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 580,
        artist_count: 90,
        subgenres: ["Country Pop", "Bluegrass", "Outlaw Country", "Contemporary Country", "Country Rock"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "8",
        name: "Latin",
        slug: "latin",
        description: "Vibrant music from Latin America featuring passionate rhythms and diverse cultural influences.",
        color: "#F97316",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 690,
        artist_count: 105,
        subgenres: ["Reggaeton", "Salsa", "Bachata", "Latin Pop", "Regional Mexican", "Cumbia"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "9",
        name: "Indie",
        slug: "indie",
        description: "Independent music characterized by creative freedom and alternative sounds.",
        color: "#06B6D4",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 540,
        artist_count: 95,
        subgenres: ["Indie Rock", "Indie Pop", "Indie Folk", "Dream Pop", "Lo-Fi"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "10",
        name: "Metal",
        slug: "metal",
        description: "Heavy, aggressive music featuring distorted guitars, powerful drums, and intense vocals.",
        color: "#DC2626",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 620,
        artist_count: 88,
        subgenres: ["Heavy Metal", "Thrash Metal", "Death Metal", "Black Metal", "Power Metal", "Metalcore"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "11",
        name: "Reggae",
        slug: "reggae",
        description: "Jamaican music featuring offbeat rhythms, bass-heavy grooves, and positive vibes.",
        color: "#16A34A",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 480,
        artist_count: 72,
        subgenres: ["Roots Reggae", "Dancehall", "Dub", "Ska", "Reggae Fusion"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "12",
        name: "Afrobeat",
        slug: "afrobeat",
        description: "Classic West African genre pioneered by Fela Kuti, blending traditional Yoruba music, jazz, funk, and highlife with political consciousness.",
        color: "#EA580C",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 320,
        artist_count: 45,
        subgenres: ["Traditional Afrobeat", "Afrobeat Jazz", "Afrobeat Funk"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "13",
        name: "Afrobeats",
        slug: "afrobeats",
        description: "Modern Nigerian and West African pop music blending African rhythms with hip-hop, R&B, dancehall, and electronic music.",
        color: "#F97316",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 850,
        artist_count: 125,
        subgenres: ["Afro-Fusion", "Afro-Pop", "Afro-Dancehall", "Afro-Highlife", "Afro-Reggae", "Afro-House"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "14",
        name: "Classical",
        slug: "classical",
        description: "Timeless orchestral and chamber music from the great composers.",
        color: "#EF4444",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 920,
        artist_count: 150,
        subgenres: ["Baroque", "Romantic", "Contemporary Classical", "Opera", "Chamber Music"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "15",
        name: "Dancehall",
        slug: "dancehall",
        description: "Jamaican dance music with electronic beats, rapid-fire vocals, and infectious rhythms.",
        color: "#FACC15",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 420,
        artist_count: 68,
        subgenres: ["Digital Dancehall", "Ragga", "Bashment", "Dancehall Pop"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "16",
        name: "Highlife",
        slug: "highlife",
        description: "West African music genre blending traditional Akan melodies with Western instruments, jazz, and swing.",
        color: "#FB923C",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 280,
        artist_count: 42,
        subgenres: ["Guitar Band Highlife", "Brass Band Highlife", "Burger Highlife", "Gospel Highlife"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "17",
        name: "Juju",
        slug: "juju",
        description: "Nigerian music style featuring talking drums, guitars, and Yoruba percussion with Islamic and Christian influences.",
        color: "#A855F7",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 210,
        artist_count: 35,
        subgenres: ["Traditional Juju", "Gospel Juju", "Modern Juju"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "18",
        name: "Fuji",
        slug: "fuji",
        description: "Nigerian percussion-based music derived from Islamic Ajisari tradition, featuring talking drums and call-and-response vocals.",
        color: "#14B8A6",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 195,
        artist_count: 28,
        subgenres: ["Traditional Fuji", "Modern Fuji", "Fuji Pop"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "19",
        name: "Apala",
        slug: "apala",
        description: "Yoruba percussion music from Nigeria featuring talking drums, with roots in Islamic wake-up music.",
        color: "#84CC16",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 165,
        artist_count: 22,
        subgenres: ["Traditional Apala", "Modern Apala"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "20",
        name: "Fado",
        slug: "fado",
        description: "Portuguese melancholic music expressing longing, fate, and nostalgia, typically featuring acoustic guitar and vocals.",
        color: "#6366F1",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 180,
        artist_count: 25,
        subgenres: ["Fado de Coimbra", "Fado de Lisboa", "Modern Fado"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "21",
        name: "Flamenco",
        slug: "flamenco",
        description: "Passionate Spanish music and dance from Andalusia featuring intricate guitar work, hand clapping, and emotional vocals.",
        color: "#DC2626",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 220,
        artist_count: 32,
        subgenres: ["Flamenco Puro", "Flamenco Fusion", "Nuevo Flamenco"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "22",
        name: "Bossa Nova",
        slug: "bossa-nova",
        description: "Brazilian music blending samba rhythms with jazz harmonies, featuring soft vocals and acoustic guitar.",
        color: "#0EA5E9",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 240,
        artist_count: 38,
        subgenres: ["Traditional Bossa Nova", "Bossa Jazz", "Modern Bossa"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "23",
        name: "Tango",
        slug: "tango",
        description: "Passionate Argentine music and dance featuring bandoneón, violin, and dramatic rhythms.",
        color: "#BE123C",
        parent_genre_id: null,
        is_approved: true,
        is_system: true,
        track_count: 200,
        artist_count: 30,
        subgenres: ["Traditional Tango", "Tango Nuevo", "Electrotango"],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ];

    let filtered = genres;

    if (input.approved_only) {
      filtered = filtered.filter((g) => g.is_approved);
    }

    if (input.parent_id) {
      filtered = filtered.filter((g) => g.parent_genre_id === input.parent_id);
    }

    if (input.search) {
      const search = input.search.toLowerCase();
      filtered = filtered.filter(
        (g) =>
          g.name.toLowerCase().includes(search) ||
          g.description?.toLowerCase().includes(search)
      );
    }

    const total = filtered.length;
    const paginated = filtered.slice(input.offset, input.offset + input.limit);

    return {
      genres: paginated,
      total,
      limit: input.limit,
      offset: input.offset,
    };
  });
