name: Simple CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  # Basic checks
  basic-checks:
    name: Basic Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type check
        run: npm run type-check

      - name: Run tests
        run: npm run test

      - name: Security audit
        run: npm run audit

      - name: Build check
        run: npm run build

  # Notify on completion
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [basic-checks]
    if: always()
    steps:
      - name: Notify success
        if: needs.basic-checks.result == 'success'
        run: |
          echo "✅ All checks passed successfully!"

      - name: Notify failure
        if: needs.basic-checks.result == 'failure'
        run: |
          echo "❌ Some checks failed. Please review the logs."
